# Generated by Django 6.0.3 on 2026-03-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorialog',
            options={'ordering': ['-fecha'], 'permissions': (('puede_ver_auditoria', 'Puede ver auditoria'),)},
        ),
    ]
