# Generated by Django 6.0.3 on 2026-03-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopostulacion',
            name='postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='postulantes.postulacion'),
        ),
    ]
