# Generated by Django 6.0.3 on 2026-03-04 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopostulacion',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentopostulacion',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cargados', to='documentos.tipodocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='documentopostulacion',
            unique_together={('postulacion', 'tipo_documento')},
        ),
    ]
