# Generated by Django 6.0.3 on 2026-03-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_initial'),
        ('modalidades', '0002_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_documento', to='modalidades.etapa'),
        ),
    ]
