# Generated by Django 6.0.3 on 2026-03-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_tipodocumento_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentopostulacion',
            options={'ordering': ['-fecha_subida'], 'permissions': (('puede_aprobar_documentos', 'Puede aprobar documentos'),)},
        ),
    ]
