# Generated by Django 6.0.3 on 2026-03-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('administ', 'Administrativo'), ('estudiante', 'Estudiante')], help_text='Campo descriptivo para interfaz/reportes. No usar para autorizacion.', max_length=20),
        ),
    ]
