# Generated by Django 6.0.3 on 2026-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('postulaciones', 'Postulaciones'), ('documentos', 'Documentos'), ('estadistico', 'Estadistico')], max_length=30)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('archivo', models.FileField(upload_to='reportes/')),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
