# Generated by Django 6.0.3 on 2026-03-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=150)),
                ('facultad', models.CharField(max_length=150)),
                ('codigo_estudiante', models.CharField(max_length=30, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_trabajo', models.CharField(max_length=255)),
                ('tutor', models.CharField(max_length=150)),
                ('gestion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revision'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='modalidades.modalidad')),
            ],
            options={
                'ordering': ['-fecha_postulacion'],
            },
        ),
    ]
