# Generated by Django 6.0.3 on 2026-03-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0002_etapa'),
        ('postulantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estado_general',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('PERFIL_APROBADO', 'Perfil aprobado'), ('PRIVADA_APROBADA', 'Privada aprobada'), ('PUBLICA_APROBADA', 'Publica aprobada'), ('TITULADO', 'Titulado')], default='EN_PROCESO', max_length=30),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='etapa_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_actuales', to='modalidades.etapa'),
        ),
    ]
