# Generated by Django 6.0.3 on 2026-03-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0003_postulacion_estado_general_postulacion_etapa_actual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulacion',
            options={'ordering': ['-fecha_postulacion'], 'permissions': (('puede_avanzar_etapa', 'Puede avanzar etapa'),)},
        ),
    ]
