# Generated by Django 5.0.3 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0004_alter_postulacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='nombre',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='apellido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
