# Generated by Django 6.0.3 on 2026-03-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='modalidades.modalidad')),
            ],
            options={
                'ordering': ['modalidad__nombre', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('modalidad', 'orden'), name='unique_orden_por_modalidad')],
            },
        ),
    ]
